import type { Workspace } from './types'

const timestamp = 1_735_689_600_000

export const workspaceMockList: Workspace[] = [
  {
    id: 'workspace-enterprise-ai',
    name: 'Enterprise AI',
    description: 'Core workspace for provider routing, runtime observability and AI operations.',
    icon: 'Cpu',
    color: '#2563eb',
    createdAt: timestamp,
    updatedAt: timestamp,
    status: 'active',
    settings: {
      defaultApplicationId: 'app-erp-copilot',
      defaultProviderId: 'provider-mock',
      enableKnowledge: true,
      enableObservability: true,
    },
    applications: ['app-erp-copilot', 'app-knowledge-qa'],
    knowledgeRefs: ['kb-runtime-docs'],
    promptRefs: ['prompt-runtime-assistant'],
    providerRefs: ['provider-mock'],
    conversationRefs: ['conversation-runtime-review'],
  },
  {
    id: 'workspace-people-ops',
    name: 'People Ops',
    description: 'Workspace for HR assistant scenarios and internal policy knowledge.',
    icon: 'User',
    color: '#16a34a',
    createdAt: timestamp + 3_600_000,
    updatedAt: timestamp + 3_600_000,
    status: 'active',
    settings: {
      defaultApplicationId: 'app-hr-assistant',
      defaultProviderId: 'provider-mock',
      enableKnowledge: true,
      enableObservability: true,
    },
    applications: ['app-hr-assistant'],
    knowledgeRefs: ['kb-hr-policy'],
    promptRefs: ['prompt-hr-assistant'],
    providerRefs: ['provider-mock'],
    conversationRefs: ['conversation-hr-policy'],
  },
  {
    id: 'workspace-revenue',
    name: 'Revenue AI',
    description: 'Workspace for CRM assistant scenarios and customer operation copilots.',
    icon: 'DataLine',
    color: '#7c3aed',
    createdAt: timestamp + 7_200_000,
    updatedAt: timestamp + 7_200_000,
    status: 'active',
    settings: {
      defaultApplicationId: 'app-crm-assistant',
      defaultProviderId: 'provider-mock',
      enableKnowledge: false,
      enableObservability: true,
    },
    applications: ['app-crm-assistant'],
    knowledgeRefs: [],
    promptRefs: ['prompt-crm-assistant'],
    providerRefs: ['provider-mock'],
    conversationRefs: ['conversation-crm-summary'],
  },
]
