import type { Application } from './Application'

const timestamp = 1_735_689_600_000

export const applicationMockList: Application[] = [
  {
    id: 'app-erp-copilot',
    workspaceId: 'workspace-enterprise-ai',
    name: 'ERP Copilot',
    description: 'Assists operators with enterprise process analysis and runtime guidance.',
    type: 'erp-copilot',
    icon: 'Operation',
    runtimeConfigId: 'runtime-enterprise-ai-default',
    providerId: 'provider-mock',
    knowledgeBaseId: 'kb-runtime-docs',
    promptTemplateId: 'prompt-runtime-assistant',
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 'app-knowledge-qa',
    workspaceId: 'workspace-enterprise-ai',
    name: 'Knowledge QA',
    description: 'Answers architecture and platform questions with citations.',
    type: 'knowledge-qa',
    icon: 'Document',
    runtimeConfigId: 'runtime-knowledge-qa',
    providerId: 'provider-mock',
    knowledgeBaseId: 'kb-runtime-docs',
    promptTemplateId: 'prompt-rag-assistant',
    createdAt: timestamp + 1_000,
    updatedAt: timestamp + 1_000,
  },
  {
    id: 'app-hr-assistant',
    workspaceId: 'workspace-people-ops',
    name: 'HR Assistant',
    description: 'Helps employees understand internal people policies.',
    type: 'hr-assistant',
    icon: 'User',
    runtimeConfigId: 'runtime-hr-default',
    providerId: 'provider-mock',
    knowledgeBaseId: 'kb-hr-policy',
    promptTemplateId: 'prompt-hr-assistant',
    createdAt: timestamp + 2_000,
    updatedAt: timestamp + 2_000,
  },
  {
    id: 'app-crm-assistant',
    workspaceId: 'workspace-revenue',
    name: 'CRM Assistant',
    description: 'Summarizes customer context and assists revenue operations.',
    type: 'crm-assistant',
    icon: 'DataLine',
    runtimeConfigId: 'runtime-crm-default',
    providerId: 'provider-mock',
    knowledgeBaseId: '',
    promptTemplateId: 'prompt-crm-assistant',
    createdAt: timestamp + 3_000,
    updatedAt: timestamp + 3_000,
  },
]
